# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\client\ui\进度窗.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(537, 99)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 501, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(33)
        self.gridLayout.setObjectName("gridLayout")
        self.label_process = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_process.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
                                        | QtCore.Qt.AlignVCenter)
        self.label_process.setObjectName("label_process")
        self.gridLayout.addWidget(self.label_process, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 33)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 2)
        self.label_test = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_test.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
                                     | QtCore.Qt.AlignVCenter)
        self.label_test.setObjectName("label_test")
        self.gridLayout.addWidget(self.label_test, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "测试进度"))
        self.label_process.setText(_translate("Dialog", "1/3"))
        self.label_test.setText(_translate("Dialog", "已测试的接口数: "))