# Generated by Django 4.1 on 2022-08-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_openid_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="nonce",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="useropenid",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
